# Generated by Django 5.0.4 on 2026-02-24 05:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineaServicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('linea_numero', models.PositiveSmallIntegerField()),
                ('estado_linea', models.CharField(choices=[('NO_INSTALADO', 'No instalado'), ('ACTIVO', 'Activo'), ('SUSPENDIDO', 'Suspendido'), ('CANCELADO', 'Cancelado')], max_length=20)),
                ('fecha_instalacion', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lineas', to='clientes.cliente')),
            ],
            options={
                'db_table': 'lineas',
                'abstract': False,
            },
        ),
    ]
