# Generated by Django 5.0.4 on 2026-02-24 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lineaservicio',
            name='saldo_vencido',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
