# Generated by Django 5.0.4 on 2026-02-24 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lineas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectionsRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField()),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SUCCESS', 'Success'), ('FAILED', 'Failed')], max_length=10)),
                ('unpaid_count', models.PositiveSmallIntegerField()),
                ('action_taken', models.CharField(blank=True, choices=[('NONE', 'None'), ('SUSPEND', 'Suspend'), ('UNSUSPEND', 'Unsuspend')], max_length=20, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='collection_logs', to='lineas.lineaservicio')),
            ],
        ),
        migrations.CreateModel(
            name='Rubro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_rubro', models.CharField(choices=[('NO_PAGADO', 'No pagado'), ('PAGADO', 'Pagado'), ('VENCIDO', 'Vencido'), ('ANULADO', 'Anulado')], default='NO_PAGADO', max_length=20)),
                ('fecha_emision', models.DateTimeField()),
                ('fecha_vencimiento', models.DateTimeField()),
                ('fecha_pago', models.DateTimeField(blank=True, null=True)),
                ('linea_servicio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rubros', to='lineas.lineaservicio')),
            ],
        ),
    ]
